# Generated by Django 5.0.6 on 2024-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_meow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
